# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from graphics import resource


class Ui_splash_screen(object):
    def setupUi(self, splash_screen):
        splash_screen.setObjectName("splash_screen")
        splash_screen.resize(700, 400)
        splash_screen.setMinimumSize(QtCore.QSize(700, 400))
        splash_screen.setMaximumSize(QtCore.QSize(700, 400))
        splash_screen.setStyleSheet("QFrame{\n"
"    background-image: url(:/Splash Screen/splash_screen.jpg);\n"
"}")
        self.image_frame = QtWidgets.QWidget(splash_screen)
        self.image_frame.setObjectName("image_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.image_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.image_frame)
        self.frame.setStyleSheet("QFrame{\n"
"    background-image: url(:/Splash Screen/splash_screen.jpg);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.loading = QtWidgets.QProgressBar(self.frame)
        self.loading.setGeometry(QtCore.QRect(80, 350, 521, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.loading.setFont(font)
        self.loading.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 8px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.loading.setProperty("value", 24)
        self.loading.setObjectName("loading")
        self.verticalLayout.addWidget(self.frame)
        splash_screen.setCentralWidget(self.image_frame)

        self.retranslateUi(splash_screen)
        QtCore.QMetaObject.connectSlotsByName(splash_screen)

    def retranslateUi(self, splash_screen):
        _translate = QtCore.QCoreApplication.translate
        splash_screen.setWindowTitle(_translate("splash_screen", "MainWindow"))

